### PR TITLE
fix(ios): no blurred images in image picker

### LINKED ISSUE #195: [iOS] images show blurred
All images show blurred in iOS, exactly as described here: https://github.com/questbeat/QBImagePicker/issues/86 (except I'm not doing multiselect, not sure if it's relevant). Since this lib is using that library, I suspect it's the same issue, but I don't understand the described workaround over there.

All iOS phones are affected (didn't try Android). 
NS 4.0.2
plugin latest version.

How can I resolve this problem?

### PR DESCRIPTION
**Pull request by JakubPawlak**
Fix for displaying blurred images in image picker when the root view of the app is any layout nesting TabView. 
Branch on which there is a reproduced bad behaviour is here:
https://github.com/JakubPawlak/nativescript-imagepicker/tree/blur

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [x] Tests for the changes are included

## What is the current behavior?

In some specific cases, image picker is showing blurred images.
https://github.com/NativeScript/nativescript-imagepicker/issues/195
## What is the new behavior?

No blurred images.

Fixes #195

No migration steps.

### CODE REVIEW

**Comment by lini** [comment]
The CI build for this PR failed because the changed code references `tns-core-modules` version 4+ and the plugin's `package.json` is still configured to use version 3:

```json
"tns-core-modules": "^3.1.0",
"tns-platform-declarations": "^3.1.0",
```

You should either update the references in package.json or make the code work without them. The error at the moment is:
```bash
$ tsc
imagepicker.ios.ts:31:46 - error TS2339: Property 'viewController' does not exist on type 'View'.

31         return this.hostView ? this.hostView.viewController : UIApplication.sharedApplication.keyWindow.rootViewController;
                                                ~~~~~~~~~~~~~~
```

**Comment by JakubPawlak** [comment]
Can I make a test CI build myself?

**Comment by lini** [comment]
The CI is public and you can view the results by going directly to https://travis-ci.org/NativeScript/nativescript-imagepicker/pull_requests
Each time you make changes to the PR, a new build will be triggered but it might take some time for it to finish, since it runs on a shared environment along with other open-source projects.

**Comment by JakubPawlak** [comment]
Ok, so I fixed package.json versions but now there are errors during UI tests... Any hints how to fix them?

**Comment by zbranzov** [comment]
https://saucelabs.com/beta/tests/5c852405baa6461d8385c6fbe447e797/commands#29
https://saucelabs.com/beta/tests/efffc2c7a84d47de8e5e9d1572450743/commands#30
Tests pass so I will merge this PR

**Pull request merged**
