### PR TITLE
feat(android): add support for mediaType option for android devices

### PR DESCRIPTION
**Pull request by xuhcc**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?

`mediaType` option only works on iOS.

## What is the new behavior?

`mediaType` option supported on Android too.

Implements #175.

### CODE REVIEW

**Comment by xuhcc** [comment]
@cla-bot check

**Comment by xuhcc** [comment]
@cla-bot check

**Comment by xuhcc** [comment]
Hi @tgpetrov 

I just tried both `npm run demo.android` and `npm run demo.ng.android` and they are working fine for me.

**Comment by xuhcc** [comment]
I also merged latest commits from master into this branch. Unfortunately `npm run demo.ng.android` started to crash after that, but it does not seem to be caused by my commit:

```
Exception in thread "main" java.lang.RuntimeException: Class not found!
	at org.nativescript.staticbindinggenerator.generating.parsing.classes.hierarchy.generics.impl.GenericsAwareClassHierarchyParserImpl.getJavaClassFromCache(GenericsAwareClassHierarchyParserImpl.java:320)
	at org.nativescript.staticbindinggenerator.generating.parsing.classes.hierarchy.generics.impl.GenericsAwareClassHierarchyParserImpl.getClassHierarchyRecursively(GenericsAwareClassHierarchyParserImpl.java:137)
	at org.nativescript.staticbindinggenerator.generating.parsing.classes.hierarchy.generics.impl.GenericsAwareClassHierarchyParserImpl.getClassHierarchy(GenericsAwareClassHierarchyParserImpl.java:54)
	at org.nativescript.staticbindinggenerator.Generator.createExtendedClassGenericHierarchyView(Generator.java:314)
	at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:290)
	at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
	at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
	at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:48)

```

**Comment by tgpetrov** [comment]
@xuhcc It seems like the issue I was hitting was related to a braking change in NativeScript CLI 6.0, so I [had to include](https://github.com/NativeScript/nativescript-imagepicker/pull/286) the ImagePickerMediaType in a ts file (and not only d.ts as until now). When I applied [your changes](https://github.com/NativeScript/nativescript-imagepicker/pull/288), the checks were successful. Thank you for your contribution!
P.S. Due to a limitation, our checks never pass when a PR is created from fork, so I'm going to merge the PR I created and close this one.

**Comment by xuhcc** [comment]
OK, thank you!

**Pull request closed without merging**
