### PR TITLE
Swap nativescript-pro-ui for nativescript-ui-listview

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Hi,

I'm aware there are plans to use a native library instead of {N} UI's RadListView (#156), but for the time being you can consider this PR, which switches to the new [nativescript-ui-listview](https://www.npmjs.com/package/nativescript-ui-listview) package so this plugin no longer drags in the entire UI library.

I've tested this change in the embedded demo app - no regression from what I've seen.

### CODE REVIEW

**Comment by jogboms** [comment]
@radeva please someone should review this PR.

**Comment by radeva** [comment]
Hi @EddyVerbruggen , @jogboms It looks like we did this also in another PR, so I'm closing this one. We're still struggling with some iOS issues though, but we expect to release a new version soon.

**Comment by EddyVerbruggen** [comment]
@radeva I didn't see that PR (still can't find it). Can you point me at it so I can subscribe (in order to get updates)?

**Comment by evanfuture** [comment]
@EddyVerbruggen Seems like this one covers it?  https://github.com/NativeScript/nativescript-imagepicker/pull/164/files

**Pull request closed without merging**
