### PR TITLE
Fix aspect ratio issue on iOS & add scaling example to docs

### PR DESCRIPTION
**Pull request by abhayastudios**
Fix aspect ratio issue on iOS where resized images were filled out instead of maintaining the aspect ratio. Also added example for scaling images to the docs.

### CODE REVIEW

**Comment by abhayastudios** [comment]
@radeva Initially the CI for this PR was passing for commit 821621defdd2df4d1f5ce837b2b939928739db35  (I only changed an enum in the code), but then something with the merge didn't work, which I don't understand. Could you please have a look? Thanks!

**Comment by abhayastudios** [comment]
@radeva any update? Thanks!

**Comment by radeva** [comment]
Hi @abhayastudios ,

Thanks for submitting a PR! My concern is that this is changing the current behaviour of the plugin which is breaking change. We'll use your idea and extend it a bit to add an option where the user can state if he/she want to use AspectFIll or AspectFit. The same way there are options for maxWidth and maxHeight. We'll let you know when this is merged and published. Let us know if this is a working solution for you.

Best regards,
Veselina

**Comment by abhayastudios** [comment]
@radeva keep in mind this is already the default behavior on Android...

**Pull request merged**
