### PR TITLE
feat(android): add video select support for android platform.

### PR DESCRIPTION
**Pull request by mylmz10**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?

Videos tabs not shown on picker area.

## What is the new behavior?

Videos tabs shown on picker area.
Implements #175, #60.

### CODE REVIEW

**Comment by tgpetrov** [comment]
@mylmz10 
Thank you for the PR.
We have a requirement that each contributor signs our CLA. Would it be ok with you to fill out [this form](https://www.nativescript.org/cla)?

**Comment by mylmz10** [comment]
@tgpetrov I fill out the form.

**Comment by elena-p** [comment]
@cla-bot check

**Comment by DimitarTodorov** [comment]
Hi @mylmz10,

I've created the same [PR](https://github.com/NativeScript/nativescript-imagepicker/pull/291), from a branch in our repo, since the CI test will not pass on PR from outside the repo due to security reasons. We will proceed with merge and will notify you once the the feature is released.

**Comment by mylmz10** [comment]
@DimitarTodorov I noticed there was one missing and I wanted to be a contributer but it was not. I see that merged and published your commit, thanks(!).

**Pull request closed without merging**
